In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import sweetviz as sv
import category_encoders as ce
import matplotlib.pyplot as plt
from collections import Counter
from sklearn.decomposition import PCA
from pandas_profiling import ProfileReport
from sklearn.preprocessing import StandardScaler
from feature_engine.encoding import OneHotEncoder
from sklearn.model_selection import train_test_split

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
heart_dis_pred = pd.read_csv("heart_cleaned_eda.csv")

In [4]:
encoder = OneHotEncoder( top_categories=1, variables=['HeartDisease','Smoking', 'AlcoholDrinking', 'Stroke', 'DiffWalking', 'Sex', 'Diabetic', 'KidneyDisease', 'SkinCancer', 'PhysicalActivity', 'Asthma'], drop_last=False)
encoder.fit(heart_dis_pred)
heart_dis_pred = encoder.transform(heart_dis_pred)

In [5]:
heart_dis_pred.head(5)

,Unnamed: 0,BMI,PhysicalHealth,MentalHealth,AgeCategory,Race,GenHealth,SleepTime,HeartDisease_No,Smoking_No,AlcoholDrinking_No,Stroke_No,DiffWalking_No,Sex_Female,Diabetic_No,KidneyDisease_No,SkinCancer_No,PhysicalActivity_Yes,Asthma_No
0,0,16.60,3,30,55-59,White,Very good,5,1,0,1,1,1,1,0,1,0,1,0
1,1,20.34,0,0,80 or older,White,Very good,7,1,1,1,0,1,1,1,1,1,1,1
2,2,26.58,20,30,65-69,White,Fair,8,1,0,1,1,1,0,0,1,1,1,0
3,3,24.21,0,0,75-79,White,Good,6,1,1,1,1,1,1,1,1,0,0,1
4,4,23.71,28,0,40-44,White,Very good,8,1,1,1,1,0,1,1,1,1,1,1

In [6]:
heart_dis_pred.shape

(319795, 19)

In [7]:
encoder = ce.BinaryEncoder(cols=['Race', 'GenHealth', 'AgeCategory'])
df_binary = encoder.fit_transform(heart_dis_pred)
df_binary.head()

,Unnamed: 0,BMI,PhysicalHealth,MentalHealth,AgeCategory_0,AgeCategory_1,AgeCategory_2,AgeCategory_3,Race_0,Race_1,Race_2,GenHealth_0,GenHealth_1,GenHealth_2,SleepTime,HeartDisease_No,Smoking_No,AlcoholDrinking_No,Stroke_No,DiffWalking_No,Sex_Female,Diabetic_No,KidneyDisease_No,SkinCancer_No,PhysicalActivity_Yes,Asthma_No
0,0,16.60,3,30,0,0,0,1,0,0,1,0,0,1,5,1,0,1,1,1,1,0,1,0,1,0
1,1,20.34,0,0,0,0,1,0,0,0,1,0,0,1,7,1,1,1,0,1,1,1,1,1,1,1
2,2,26.58,20,30,0,0,1,1,0,0,1,0,1,0,8,1,0,1,1,1,0,0,1,1,1,0
3,3,24.21,0,0,0,1,0,0,0,0,1,0,1,1,6,1,1,1,1,1,1,1,1,0,0,1
4,4,23.71,28,0,0,1,0,1,0,0,1,0,0,1,8,1,1,1,1,0,1,1,1,1,1,1

In [8]:
df_binary.shape

(319795, 26)

In [9]:
df_binary.to_csv("heart_cleaned_encoded.csv")